wp.domReady(function() {
	wp.blocks.unregisterBlockStyle('core/button', 'default');
	wp.blocks.unregisterBlockStyle('core/button', 'outline');
	wp.blocks.unregisterBlockStyle('core/button', 'squared');
	wp.blocks.unregisterBlockStyle('core/pullquote', 'default');
	wp.blocks.unregisterBlockStyle('core/pullquote', 'solid-color');
	wp.blocks.unregisterBlockStyle('core/quote', 'default');
	wp.blocks.unregisterBlockStyle('core/quote', 'large');
	wp.blocks.unregisterBlockStyle('core/table', 'default');
	wp.blocks.unregisterBlockStyle('core/table', 'stripes');

	wp.blocks.unregisterBlockType('core/archives');
	wp.blocks.unregisterBlockType('core/calendar');
	wp.blocks.unregisterBlockType('core/columns');
	wp.blocks.unregisterBlockType('core/cover');
	wp.blocks.unregisterBlockType('core/heading');
	wp.blocks.unregisterBlockType('core/latest-comments');
	wp.blocks.unregisterBlockType('core/list');
	wp.blocks.unregisterBlockType('core/more');
	wp.blocks.unregisterBlockType('core/nextpage');
	wp.blocks.unregisterBlockType('core/paragraph');
	wp.blocks.unregisterBlockType('core/search');
	wp.blocks.unregisterBlockType('core/shortcode');
	wp.blocks.unregisterBlockType('core/spacer');
	wp.blocks.unregisterBlockType('core/tag-cloud');
	wp.blocks.unregisterBlockType('core/verse');
	wp.blocks.unregisterBlockType('core-embed/amazon-kindle');
	wp.blocks.unregisterBlockType('core-embed/animoto');
	wp.blocks.unregisterBlockType('core-embed/cloudup');
	wp.blocks.unregisterBlockType('core-embed/collegehumor');
	wp.blocks.unregisterBlockType('core-embed/crowdsignal');
	wp.blocks.unregisterBlockType('core-embed/dailymotion');
	wp.blocks.unregisterBlockType('core-embed/instagram');
	wp.blocks.unregisterBlockType('core-embed/facebook');
	wp.blocks.unregisterBlockType('core-embed/soundcloud');
	wp.blocks.unregisterBlockType('core-embed/spotify');
	wp.blocks.unregisterBlockType('core-embed/hulu');
	wp.blocks.unregisterBlockType('core-embed/imgur');
	wp.blocks.unregisterBlockType('core-embed/issuu');
	wp.blocks.unregisterBlockType('core-embed/kickstarter');
	wp.blocks.unregisterBlockType('core-embed/meetup-com');
	wp.blocks.unregisterBlockType('core-embed/mixcloud');
	wp.blocks.unregisterBlockType('core-embed/polldaddy');
	wp.blocks.unregisterBlockType('core-embed/reddit');
	wp.blocks.unregisterBlockType('core-embed/reverbnation');
	wp.blocks.unregisterBlockType('core-embed/screencast');
	wp.blocks.unregisterBlockType('core-embed/scribd');
	wp.blocks.unregisterBlockType('core-embed/slideshare');
	wp.blocks.unregisterBlockType('core-embed/smugmug');
	wp.blocks.unregisterBlockType('core-embed/speaker-deck');
	wp.blocks.unregisterBlockType('core-embed/ted');
	wp.blocks.unregisterBlockType('core-embed/tumblr');
	wp.blocks.unregisterBlockType('core-embed/videopress');
	wp.blocks.unregisterBlockType('core-embed/wordpress');
	wp.blocks.unregisterBlockType('core-embed/wordpress-tv');
});